/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Inicio.PInicio;
import Cliente.JPCliente;

import Empleado.CEmpleado;
import Empleado.JPEmpleado;

import HorariosE.JPHorariosE;
import FormaPago.JPFormaPago;

import Marca.JPMarca;

import Usuario.CUsuario;

import Producto.PProducto;

import TipoProducto.JPTipoProducto;

import Stock.PStock;

import Usuario.JPCambiarContraseña;
import Usuario.JPCambiarNombre;
import Consultas.JPConsultas;

import Venta.JPVentaProductos;
import Venta.JPVerFacturasXCliente;

import java.awt.Toolkit;
import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author German Bartoli
 */
public class JFMenuPrincipal extends javax.swing.JFrame {

    PInicio panelInicio;

    PProducto panelProducto;

    PStock panelStock;

    JPTipoProducto jPTipoProducto;
    JPMarca jPMarca;
    JPFormaPago jPFormaPago;

    JPEmpleado jPEmpleado;
    JPHorariosE jPHorariosE;

    JPCliente jPCliente;

    JPCambiarContraseña jPCambiarContraseña;
    JPCambiarNombre jPCambiarNombre;

    JPVentaProductos jPVentaProductos;
    JPVerFacturasXCliente jPVerFacturasXCliente;

    JPConsultas jPConsultas;

    private static CUsuario usuario;
    private static CEmpleado empleado;

    /**
     * Creates new form MenuPrincipal
     *
     * @param usuario
     * @param empleado
     */
    public JFMenuPrincipal(CUsuario usuario, CEmpleado empleado) {
        initComponents();

        JFMenuPrincipal.usuario = usuario;
        JFMenuPrincipal.empleado = empleado;
        jMBienvenido.setText("|| Usuario: " + usuario.getNombre() + " || Empleado: " + empleado.getApellido() + ", " + empleado.getNombre() + " ||");

        this.setLocationRelativeTo(null);

        this.panelInicio = new PInicio();
        JPContenedor.add(panelInicio);

        this.setIconImage(Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes\\Icono.png")));

        setVisible(true);
    }

    private void RemoveAllValidate() {
        JPContenedor.removeAll();
        JPContenedor.validate();
    }

    private void AgregarPanel(JPanel panel) {
        JPContenedor.add(panel);
        panel.setVisible(true);
        JPContenedor.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPContenedor = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMInicio = new javax.swing.JMenu();
        jMFacturacion = new javax.swing.JMenu();
        jMVentaProductos = new javax.swing.JMenuItem();
        jMIConsultarFacturasXCliente = new javax.swing.JMenuItem();
        jMProductos = new javax.swing.JMenu();
        jMStocks = new javax.swing.JMenu();
        jMClientes = new javax.swing.JMenu();
        jMEmpleados = new javax.swing.JMenu();
        jMHorarios = new javax.swing.JMenu();
        JMConsultas = new javax.swing.JMenu();
        jMOtros = new javax.swing.JMenu();
        jMIMarca = new javax.swing.JMenuItem();
        jMITipoProducto = new javax.swing.JMenuItem();
        jMIFormaPago = new javax.swing.JMenuItem();
        jMenuItemManualUsuario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMBienvenido = new javax.swing.JMenu();
        jMUsuario = new javax.swing.JMenu();
        jMenuItemCambiarNombre = new javax.swing.JMenuItem();
        jMenuItemCambiarContraseña = new javax.swing.JMenuItem();
        jMenuItemCerrarSesión = new javax.swing.JMenuItem();
        jMMinimizar = new javax.swing.JMenu();
        jMCerrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setResizable(false);

        JPContenedor.setBackground(new java.awt.Color(0, 0, 0));
        JPContenedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        JPContenedor.setMaximumSize(new java.awt.Dimension(1280, 695));
        JPContenedor.setPreferredSize(new java.awt.Dimension(1280, 695));
        JPContenedor.setLayout(new java.awt.BorderLayout());

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(1280, 23));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(1280, 23));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(1280, 23));

        jMInicio.setText("Inicio");
        jMInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMInicio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMInicio.setNextFocusableComponent(jMFacturacion);
        jMInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMInicio);

        jMFacturacion.setText("Facturación");
        jMFacturacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMFacturacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMVentaProductos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMVentaProductos.setText("Nueva Venta");
        jMVentaProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMVentaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVentaProductosActionPerformed(evt);
            }
        });
        jMFacturacion.add(jMVentaProductos);

        jMIConsultarFacturasXCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMIConsultarFacturasXCliente.setText("Ver Facturas de Clientes");
        jMIConsultarFacturasXCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMIConsultarFacturasXCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIConsultarFacturasXClienteActionPerformed(evt);
            }
        });
        jMFacturacion.add(jMIConsultarFacturasXCliente);

        jMenuBar1.add(jMFacturacion);

        jMProductos.setText("Productos");
        jMProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMProductos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMProductosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMProductos);

        jMStocks.setText("Stocks");
        jMStocks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMStocks.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMStocks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMStocksMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMStocks);

        jMClientes.setText("Clientes");
        jMClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMClientes.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMClientesMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMClientes);

        jMEmpleados.setText("Empleados");
        jMEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMEmpleados.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMEmpleadosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMEmpleados);

        jMHorarios.setText("Horarios");
        jMHorarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMHorarios.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMHorariosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMHorarios);

        JMConsultas.setText("Consultas");
        JMConsultas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JMConsultas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JMConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JMConsultasMouseClicked(evt);
            }
        });
        jMenuBar1.add(JMConsultas);

        jMOtros.setText("Otros");
        jMOtros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMOtros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMIMarca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMIMarca.setText("Marca");
        jMIMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMIMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIMarcaActionPerformed(evt);
            }
        });
        jMOtros.add(jMIMarca);

        jMITipoProducto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMITipoProducto.setText("Tipo Producto");
        jMITipoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMITipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMITipoProductoActionPerformed(evt);
            }
        });
        jMOtros.add(jMITipoProducto);

        jMIFormaPago.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMIFormaPago.setText("Forma de Pago");
        jMIFormaPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMIFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormaPagoActionPerformed(evt);
            }
        });
        jMOtros.add(jMIFormaPago);

        jMenuItemManualUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItemManualUsuario.setText("Manual Usuario");
        jMenuItemManualUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemManualUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManualUsuarioActionPerformed(evt);
            }
        });
        jMOtros.add(jMenuItemManualUsuario);

        jMenuBar1.add(jMOtros);

        jMenu3.setEnabled(false);
        jMenuBar1.add(jMenu3);

        jMenu1.setEnabled(false);
        jMenu1.setMinimumSize(new java.awt.Dimension(200, 5));
        jMenu1.setPreferredSize(new java.awt.Dimension(200, 5));
        jMenuBar1.add(jMenu1);

        jMBienvenido.setBackground(new java.awt.Color(0, 0, 0));
        jMBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        jMBienvenido.setText("Usuario: - Empleado: ");
        jMBienvenido.setEnabled(false);
        jMBienvenido.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMBienvenido.setMaximumSize(new java.awt.Dimension(500, 32767));
        jMBienvenido.setPreferredSize(new java.awt.Dimension(200, 21));
        jMenuBar1.add(jMBienvenido);

        jMUsuario.setText("Usuario");
        jMUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenuItemCambiarNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItemCambiarNombre.setText("Cambiar Nombre");
        jMenuItemCambiarNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCambiarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarNombreActionPerformed(evt);
            }
        });
        jMUsuario.add(jMenuItemCambiarNombre);

        jMenuItemCambiarContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItemCambiarContraseña.setText("Cambiar Contraseña");
        jMenuItemCambiarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCambiarContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCambiarContraseñaActionPerformed(evt);
            }
        });
        jMUsuario.add(jMenuItemCambiarContraseña);

        jMenuItemCerrarSesión.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMenuItemCerrarSesión.setText("Cerrar Sesión");
        jMenuItemCerrarSesión.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCerrarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCerrarSesiónActionPerformed(evt);
            }
        });
        jMUsuario.add(jMenuItemCerrarSesión);

        jMenuBar1.add(jMUsuario);

        jMMinimizar.setText("Minimizar");
        jMMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMMinimizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMMinimizarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMMinimizar);

        jMCerrar.setText("Salir");
        jMCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMCerrar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jMCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMCerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMCerrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCambiarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarContraseñaActionPerformed
        // TODO add your handling code here:
        RemoveAllValidate();

        jPCambiarContraseña = new JPCambiarContraseña(usuario);

        AgregarPanel(jPCambiarContraseña);
    }//GEN-LAST:event_jMenuItemCambiarContraseñaActionPerformed

    private void jMenuItemCerrarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCerrarSesiónActionPerformed
        // TODO add your handling code here:

        int option = JOptionPane.showConfirmDialog(
                null,
                "¿Desea Cerrar Sesión?",
                "Alerta!",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.YES_OPTION) {
            this.dispose();
            JFLogin login = new JFLogin();
        }
    }//GEN-LAST:event_jMenuItemCerrarSesiónActionPerformed

    private void jMenuItemCambiarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCambiarNombreActionPerformed
        // TODO add your handling code here:
        RemoveAllValidate();

        jPCambiarNombre = new JPCambiarNombre(usuario);

        AgregarPanel(jPCambiarNombre);
    }//GEN-LAST:event_jMenuItemCambiarNombreActionPerformed

    private void jMITipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMITipoProductoActionPerformed
        // TODO add your handling code here:
        RemoveAllValidate();

        jPTipoProducto = new JPTipoProducto();

        AgregarPanel(jPTipoProducto);
    }//GEN-LAST:event_jMITipoProductoActionPerformed

    private void jMIMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIMarcaActionPerformed
        // TODO add your handling code here:
        RemoveAllValidate();

        jPMarca = new JPMarca();

        AgregarPanel(jPMarca);
    }//GEN-LAST:event_jMIMarcaActionPerformed

    private void jMMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMMinimizarMouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jMMinimizarMouseClicked

    private void jMCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMCerrarMouseClicked
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(
                null,
                "¿Está Seguro?",
                "Saliendo de Nona Mafalda Software",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMCerrarMouseClicked

    private void jMInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMInicioMouseClicked
        // TODO add your handling code here:
        //OcultarPanelAbierto();

        JPContenedor.removeAll();
        JPContenedor.validate();

        panelInicio = new PInicio();

        JPContenedor.add(panelInicio);
        panelInicio.setVisible(true);
        JPContenedor.validate();
    }//GEN-LAST:event_jMInicioMouseClicked

    private void jMIFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormaPagoActionPerformed
        // TODO add your handling code here:

        RemoveAllValidate();

        jPFormaPago = new JPFormaPago();

        AgregarPanel(jPFormaPago);


    }//GEN-LAST:event_jMIFormaPagoActionPerformed

    private void jMStocksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMStocksMouseClicked
        // TODO add your handling code here:

        RemoveAllValidate();

        panelStock = new PStock();

        AgregarPanel(panelStock);
    }//GEN-LAST:event_jMStocksMouseClicked

    private void jMClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMClientesMouseClicked
        // TODO add your handling code here:
        RemoveAllValidate();

        jPCliente = new JPCliente();

        AgregarPanel(jPCliente);
    }//GEN-LAST:event_jMClientesMouseClicked

    private void jMProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMProductosMouseClicked
        // TODO add your handling code here:
        RemoveAllValidate();

        panelProducto = new PProducto();

        AgregarPanel(panelProducto);
    }//GEN-LAST:event_jMProductosMouseClicked

    private void jMHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMHorariosMouseClicked
        // TODO add your handling code here:
        RemoveAllValidate();
        jPHorariosE = new JPHorariosE();
        AgregarPanel(jPHorariosE);
    }//GEN-LAST:event_jMHorariosMouseClicked

    private void jMEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMEmpleadosMouseClicked
        // TODO add your handling code here:
        RemoveAllValidate();

        jPEmpleado = new JPEmpleado(usuario);

        AgregarPanel(jPEmpleado);
    }//GEN-LAST:event_jMEmpleadosMouseClicked

    private void JMConsultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JMConsultasMouseClicked
        // TODO add your handling code here:
        RemoveAllValidate();

        jPConsultas = new JPConsultas();

        AgregarPanel(jPConsultas);
    }//GEN-LAST:event_JMConsultasMouseClicked

    private void jMVentaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVentaProductosActionPerformed
        // TODO add your handling code here:
        RemoveAllValidate();

        jPVentaProductos = new JPVentaProductos(empleado);

        AgregarPanel(jPVentaProductos);
    }//GEN-LAST:event_jMVentaProductosActionPerformed

    private void jMIConsultarFacturasXClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIConsultarFacturasXClienteActionPerformed
        // TODO add your handling code here:
        RemoveAllValidate();

        jPVerFacturasXCliente = new JPVerFacturasXCliente();

        AgregarPanel(jPVerFacturasXCliente);
    }//GEN-LAST:event_jMIConsultarFacturasXClienteActionPerformed

    private void jMenuItemManualUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManualUsuarioActionPerformed
        // TODO add your handling code here:
        //Tiene que estar en el c
        try {

            if ((new File("c:\\Manual-de-Usuario.pdf")).exists()) {

                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler c:\\Manual-de-Usuario.pdf");
                p.waitFor();

            } else {

                System.out.println("File is not exists");

            }

            System.out.println("Manual de Usuario Abierto con Exito");

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemManualUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenuPrincipal(usuario, empleado).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMConsultas;
    private javax.swing.JPanel JPContenedor;
    private javax.swing.JMenu jMBienvenido;
    private javax.swing.JMenu jMCerrar;
    private javax.swing.JMenu jMClientes;
    private javax.swing.JMenu jMEmpleados;
    private javax.swing.JMenu jMFacturacion;
    private javax.swing.JMenu jMHorarios;
    private javax.swing.JMenuItem jMIConsultarFacturasXCliente;
    private javax.swing.JMenuItem jMIFormaPago;
    private javax.swing.JMenuItem jMIMarca;
    private javax.swing.JMenuItem jMITipoProducto;
    private javax.swing.JMenu jMInicio;
    private javax.swing.JMenu jMMinimizar;
    private javax.swing.JMenu jMOtros;
    private javax.swing.JMenu jMProductos;
    private javax.swing.JMenu jMStocks;
    private javax.swing.JMenu jMUsuario;
    private javax.swing.JMenuItem jMVentaProductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemCambiarContraseña;
    private javax.swing.JMenuItem jMenuItemCambiarNombre;
    private javax.swing.JMenuItem jMenuItemCerrarSesión;
    private javax.swing.JMenuItem jMenuItemManualUsuario;
    // End of variables declaration//GEN-END:variables
}
