/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Marca;

import Modelos.TextPrompt;
import Modelos.ValidacionesCampos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author German Bartoli
 */
public class JPMarca extends javax.swing.JPanel {

    private final GBDMarca gestorBDMarca;

    private DefaultListModel<CMarca> listModel;

    private ArrayList<CMarca> alMarcas;
    private ListSelectionListener lslMarcas;

    boolean banderaAgregarEditar;

    /**
     * Creates new form JPMarca
     */
    public JPMarca() {
        initComponents();

        gestorBDMarca = new GBDMarca();

        CrearListSelectionListenerListaMarcas();

        CargarLista();

        ValidacionCampos();

        //No copy/paste
        jTFMarca.setTransferHandler(null);

        TextPrompt placeHolderCantidad = new TextPrompt(
                "Marca de Producto",
                jTFMarca,
                TextPrompt.Show.ALWAYS
        );
    }

    public void CargarLista() {
        alMarcas = gestorBDMarca.CargarListaMarcas();

        jLMarcas.removeListSelectionListener(lslMarcas);

        //Crear un objeto DefaultListModel
        listModel = new DefaultListModel<CMarca>();

        //Recorrer el contenido del ArrayList
        for (int i = 0; i < alMarcas.size(); i++) {
            //Añadir cada elemento del ArrayList en el modelo de la lista
            listModel.add(i, alMarcas.get(i));
        }
        //Asociar el modelo de lista al JList
        jLMarcas.setModel(listModel);

        jLMarcas.addListSelectionListener(lslMarcas);

        if (jLMarcas.getModel().getSize() > 0) {
            HabilitarDeshabilitarCampos(false);
            jLMarcas.setEnabled(true);

            HabilitarDeshabilitarBotones(true);
            jBGuardar.setEnabled(false);
            jBCancelar.setEnabled(false);

            jLMarcas.setSelectedIndex(0);
        } else {
            HabilitarDeshabilitarCampos(false);

            HabilitarDeshabilitarBotones(false);
            jBAgregar.setEnabled(true);

            LimpiarCampos();
        }
    }

    private void CrearListSelectionListenerListaMarcas() {
        lslMarcas = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
                    if (jLMarcas.getModel().getSize() > 0) {
                        LimpiarCampos();
                        SeleccionarItemLista();
                    }
                }
            }
        };
    }

    protected void SeleccionarItemLista() {
        if (jLMarcas.getModel().getSize() != 0) {
            jTFMarca.setText(jLMarcas.getSelectedValue().getNombre());
        }
    }

    private void LimpiarCampos() {
        jTFMarca.setText("");
    }

    private void HabilitarDeshabilitarCampos(boolean x) {
        jTFMarca.setEnabled(x);
        jLMarcas.setEnabled(x);
    }

    private void HabilitarDeshabilitarBotones(boolean x) {
        jBAgregar.setEnabled(x);
        jBEditar.setEnabled(x);
        jBBorrar.setEnabled(x);
        jBGuardar.setEnabled(x);
        jBCancelar.setEnabled(x);
    }

    //Validar numeros y letras, agregar mensaje si no quiere agregarlo
    private boolean validar() {
        if (jTFMarca.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Marca Incorrecta",
                    "Advertencia - Nona Mafalda",
                    JOptionPane.WARNING_MESSAGE);
            jTFMarca.requestFocus();
            return false;
        }
        return true;
    }

    private void ValidacionCampos() {
        ValidacionesCampos.MayusculasMinusculasNumerosEspaciosBorrar40(jTFMarca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLMarcas = new javax.swing.JList<>();
        jBEditar = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBGuardar = new javax.swing.JButton();
        jBAgregar = new javax.swing.JButton();
        jTFMarca = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        jLMarcas.setBackground(new java.awt.Color(0, 0, 0));
        jLMarcas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLMarcas.setForeground(new java.awt.Color(255, 255, 255));
        jLMarcas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLMarcas.setToolTipText("Listado de Marcas");
        jLMarcas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLMarcas.setNextFocusableComponent(jTFMarca);
        jLMarcas.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jLMarcas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jLMarcas);

        add(jScrollPane1);
        jScrollPane1.setBounds(390, 100, 480, 430);

        jBEditar.setBackground(new java.awt.Color(0, 0, 0));
        jBEditar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jBEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBEditar.setText("Editar");
        jBEditar.setToolTipText("Editar Marca Seleccionada");
        jBEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEditar.setNextFocusableComponent(jBBorrar);
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        add(jBEditar);
        jBEditar.setBounds(360, 610, 180, 60);

        jBBorrar.setBackground(new java.awt.Color(0, 0, 0));
        jBBorrar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jBBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jBBorrar.setText("Borrar");
        jBBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBorrar.setNextFocusableComponent(jBGuardar);
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });
        add(jBBorrar);
        jBBorrar.setBounds(550, 610, 180, 60);

        jBCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jBCancelar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jBCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBCancelar.setText("Cancelar");
        jBCancelar.setToolTipText("Cancelar Operacion");
        jBCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCancelar.setNextFocusableComponent(jLMarcas);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        add(jBCancelar);
        jBCancelar.setBounds(930, 610, 180, 60);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marca");
        add(jLabel2);
        jLabel2.setBounds(560, 30, 140, 50);

        jBGuardar.setBackground(new java.awt.Color(0, 0, 0));
        jBGuardar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBGuardar.setText("Guardar");
        jBGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGuardar.setNextFocusableComponent(jBCancelar);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        add(jBGuardar);
        jBGuardar.setBounds(740, 610, 180, 60);

        jBAgregar.setBackground(new java.awt.Color(0, 0, 0));
        jBAgregar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jBAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregar.setText("Agregar");
        jBAgregar.setToolTipText("Agregar Marca");
        jBAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregar.setNextFocusableComponent(jBEditar);
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        add(jBAgregar);
        jBAgregar.setBounds(170, 610, 180, 60);

        jTFMarca.setBackground(new java.awt.Color(0, 0, 0));
        jTFMarca.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTFMarca.setForeground(new java.awt.Color(255, 255, 255));
        jTFMarca.setToolTipText("Marca");
        jTFMarca.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFMarca.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTFMarca.setNextFocusableComponent(jBAgregar);
        jTFMarca.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTFMarca.setSelectionColor(new java.awt.Color(255, 255, 255));
        add(jTFMarca);
        jTFMarca.setBounds(390, 550, 480, 39);
    }// </editor-fold>//GEN-END:initComponents

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
        if (jLMarcas.getModel().getSize() > 0) {
            banderaAgregarEditar = false;

            HabilitarDeshabilitarCampos(true);
            jLMarcas.setEnabled(false);

            HabilitarDeshabilitarBotones(false);
            jBGuardar.setEnabled(true);
            jBCancelar.setEnabled(true);

            jTFMarca.requestFocus();
        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        // TODO add your handling code here:
        if (jLMarcas.getModel().getSize() > 0) {
            if (JOptionPane.showConfirmDialog(
                    this,
                    "Esta seguro?",
                    "Eliminando Tipo Producto - Nona Mafalda",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                // yes option
                int idMarca = jLMarcas.getSelectedValue().getId_Marca();
                boolean exito = false;

                exito = gestorBDMarca.EliminarMarca(idMarca);

                if (exito) {
                    JOptionPane.showMessageDialog(
                            this,
                            "La Marca se eliminó correctamente.",
                            "Exito - Nona Mafalda",
                            JOptionPane.INFORMATION_MESSAGE);

                    CargarLista();

                } else {
                    JOptionPane.showConfirmDialog(
                            this,
                            "Intentelo Nuevamente.",
                            "Error al Eliminar el Tipo de Producto - Nona Mafalda",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jBBorrarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:

        HabilitarDeshabilitarCampos(false);
        jLMarcas.setEnabled(true);

        HabilitarDeshabilitarBotones(true);
        jBGuardar.setEnabled(false);
        jBCancelar.setEnabled(false);

        if (jLMarcas.getModel().getSize() != 0) {
            jLMarcas.setSelectedIndex(jLMarcas.getSelectedIndex());
            SeleccionarItemLista();

        } else {
            jBBorrar.setEnabled(false);
            jBEditar.setEnabled(false);

            LimpiarCampos();
        }

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        if (validar()) {

            int idMarca;

            if (banderaAgregarEditar) {
                idMarca = -1;
            } else {
                idMarca = jLMarcas.getSelectedValue().getId_Marca();
            }

            String nombre = jTFMarca.getText();

            CMarca marca = new CMarca(idMarca, nombre, true);

              if (banderaAgregarEditar) {
                if (gestorBDMarca.ExisteNombreMarcaAgregar(marca)) {
                    JOptionPane.showMessageDialog(
                            this,
                            "¡Marca Repetida!",
                            "Advertencia - Nona Mafalda",
                            JOptionPane.WARNING_MESSAGE);
                    jTFMarca.requestFocus();
                    return;
                }
            } else {
                if (gestorBDMarca.ExisteNombreMarcaEditar(marca)) {
                    JOptionPane.showMessageDialog(
                            this,
                            "¡Marca Repetida!",
                            "Advertencia - Nona Mafalda",
                            JOptionPane.WARNING_MESSAGE);
                    jTFMarca.requestFocus();
                    return;
                }
            }

            boolean exito = false;

            if (idMarca == -1) {
                exito = gestorBDMarca.AgregarMarca(marca);
            } else {
                try {
                    exito = gestorBDMarca.ModificarMarca(marca);
                } catch (SQLException ex) {
                    Logger.getLogger(JPMarca.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if (exito) {
                JOptionPane.showMessageDialog(
                        this,
                        "La Marca se guardó Correctamente",
                        "Exito - Nona Mafalda",
                        JOptionPane.INFORMATION_MESSAGE);

                CargarLista();

                for (int i = 0; i < jLMarcas.getModel().getSize(); i++) {
                    if (jLMarcas.getModel().getElementAt(i).getNombre().equals(nombre)) {
                        jLMarcas.setSelectedIndex(i);
                    }
                }
            }
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
        banderaAgregarEditar = true;
        LimpiarCampos();

        HabilitarDeshabilitarCampos(true);
        jLMarcas.setEnabled(false);

        HabilitarDeshabilitarBotones(false);
        jBGuardar.setEnabled(true);
        jBCancelar.setEnabled(true);

        jTFMarca.requestFocus();
    }//GEN-LAST:event_jBAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JList<Marca.CMarca> jLMarcas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFMarca;
    // End of variables declaration//GEN-END:variables
}
