/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormaPago;

import Modelos.TextPrompt;
import Modelos.ValidacionesCampos;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author German Bartoli
 */
public class JPFormaPago extends javax.swing.JPanel {

    private final GBDFormaPago GBDFormaPago;

    private DefaultListModel<CFormaPago> listModel;

    private ArrayList<CFormaPago> alFormasPago;
    private ListSelectionListener lslFormasPago;

    boolean banderaAgregarEditar;

    /**
     * Creates new form JPFormaPago
     */
    public JPFormaPago() {
        initComponents();

        GBDFormaPago = new GBDFormaPago();

        CrearListSelectionListenerListaFormasPago();

        CargarLista();

        ValidacionCampos();

        //No copy/paste
        jTFFormaPago.setTransferHandler(null);

        TextPrompt placeHolderCantidad = new TextPrompt(
                "Forma de Pago",
                jTFFormaPago,
                TextPrompt.Show.ALWAYS
        );
    }

    public void CargarLista() {
        alFormasPago = GBDFormaPago.CargarListaFormasPago();

        jLFormaPago.removeListSelectionListener(lslFormasPago);

        //Crear un objeto DefaultListModel
        listModel = new DefaultListModel<CFormaPago>();

        //Recorrer el contenido del ArrayList
        for (int i = 0; i < alFormasPago.size(); i++) {
            //Añadir cada elemento del ArrayList en el modelo de la lista
            listModel.add(i, alFormasPago.get(i));
        }
        //Asociar el modelo de lista al JList
        jLFormaPago.setModel(listModel);

        jLFormaPago.addListSelectionListener(lslFormasPago);

        if (jLFormaPago.getModel().getSize() > 0) {
            HabilitarDeshabilitarCampos(false);
            jLFormaPago.setEnabled(true);

            HabilitarDeshabilitarBotones(true);
            jBGuardar.setEnabled(false);
            jBCancelar.setEnabled(false);

            jLFormaPago.setSelectedIndex(0);
        } else {
            HabilitarDeshabilitarCampos(false);

            HabilitarDeshabilitarBotones(false);
            jBAgregar.setEnabled(true);

            LimpiarCampos();
        }
    }

    private void CrearListSelectionListenerListaFormasPago() {
        lslFormasPago = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
                    if (jLFormaPago.getModel().getSize() > 0) {
                        LimpiarCampos();
                        SeleccionarItemLista();
                    }
                }
            }
        };
    }

    protected void SeleccionarItemLista() {
        if (jLFormaPago.getModel().getSize() > 0) {
            jTFFormaPago.setText(jLFormaPago.getSelectedValue().getFormaPago());
        }
    }

    private void LimpiarCampos() {
        jTFFormaPago.setText("");
    }

    private void HabilitarDeshabilitarCampos(boolean x) {
        jTFFormaPago.setEnabled(x);
        jLFormaPago.setEnabled(x);
    }

    private void HabilitarDeshabilitarBotones(boolean x) {
        jBAgregar.setEnabled(x);
        jBEditar.setEnabled(x);
        jBBorrar.setEnabled(x);
        jBGuardar.setEnabled(x);
        jBCancelar.setEnabled(x);
    }

    //Validar numeros y letras, agregar mensaje si no quiere agregarlo
    private boolean validar() {
        if (jTFFormaPago.getText().equals("")) {
            JOptionPane.showMessageDialog(
                    this,
                    "Forma de Pago Incorrecta",
                    "Advertencia - Nona Mafalda",
                    JOptionPane.WARNING_MESSAGE);
            jTFFormaPago.requestFocus();
            return false;
        }
        return true;
    }

    private void ValidacionCampos() {
        ValidacionesCampos.MayusculasMinusculasNumerosEspaciosBorrar40(jTFFormaPago);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jBEditar = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBAgregar = new javax.swing.JButton();
        jTFFormaPago = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLFormaPago = new javax.swing.JList<>();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Forma de Pago");
        add(jLabel2);
        jLabel2.setBounds(430, 30, 332, 56);

        jBEditar.setBackground(new java.awt.Color(0, 0, 0));
        jBEditar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jBEditar.setForeground(new java.awt.Color(255, 255, 255));
        jBEditar.setText("Editar");
        jBEditar.setToolTipText("Editar Forma de Pago Seleccionada");
        jBEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBEditar.setNextFocusableComponent(jBBorrar);
        jBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarActionPerformed(evt);
            }
        });
        add(jBEditar);
        jBEditar.setBounds(340, 610, 180, 60);

        jBBorrar.setBackground(new java.awt.Color(0, 0, 0));
        jBBorrar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jBBorrar.setForeground(new java.awt.Color(255, 255, 255));
        jBBorrar.setText("Borrar");
        jBBorrar.setToolTipText("Borrar Forma de Pago Seleccionada");
        jBBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBBorrar.setNextFocusableComponent(jBGuardar);
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });
        add(jBBorrar);
        jBBorrar.setBounds(530, 610, 180, 60);

        jBCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jBCancelar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jBCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBCancelar.setText("Cancelar");
        jBCancelar.setToolTipText("Cancelar Operación");
        jBCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBCancelar.setNextFocusableComponent(jLFormaPago);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        add(jBCancelar);
        jBCancelar.setBounds(920, 610, 180, 60);

        jBGuardar.setBackground(new java.awt.Color(0, 0, 0));
        jBGuardar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jBGuardar.setText("Guardar");
        jBGuardar.setToolTipText("Guardar Forma de Pago");
        jBGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBGuardar.setNextFocusableComponent(jBCancelar);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        add(jBGuardar);
        jBGuardar.setBounds(720, 610, 180, 60);

        jBAgregar.setBackground(new java.awt.Color(0, 0, 0));
        jBAgregar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jBAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregar.setText("Agregar");
        jBAgregar.setToolTipText("Agregar Forma de Pago");
        jBAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAgregar.setNextFocusableComponent(jBEditar);
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        add(jBAgregar);
        jBAgregar.setBounds(140, 610, 180, 60);

        jTFFormaPago.setBackground(new java.awt.Color(0, 0, 0));
        jTFFormaPago.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTFFormaPago.setForeground(new java.awt.Color(255, 255, 255));
        jTFFormaPago.setToolTipText("Forma de Pago");
        jTFFormaPago.setCaretColor(new java.awt.Color(255, 255, 255));
        jTFFormaPago.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTFFormaPago.setNextFocusableComponent(jBAgregar);
        jTFFormaPago.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTFFormaPago.setSelectionColor(new java.awt.Color(255, 255, 255));
        add(jTFFormaPago);
        jTFFormaPago.setBounds(370, 540, 480, 39);

        jLFormaPago.setBackground(new java.awt.Color(0, 0, 0));
        jLFormaPago.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLFormaPago.setForeground(new java.awt.Color(255, 255, 255));
        jLFormaPago.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLFormaPago.setToolTipText("Listado de Formas de Pago");
        jLFormaPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLFormaPago.setNextFocusableComponent(jTFFormaPago);
        jLFormaPago.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jLFormaPago.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jLFormaPago);

        add(jScrollPane1);
        jScrollPane1.setBounds(370, 100, 480, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void jBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarActionPerformed
        // TODO add your handling code here:
        if (jLFormaPago.getModel().getSize() > 0) {

            banderaAgregarEditar = false;

            HabilitarDeshabilitarCampos(true);
            jLFormaPago.setEnabled(false);

            HabilitarDeshabilitarBotones(false);
            jBGuardar.setEnabled(true);
            jBCancelar.setEnabled(true);

            jTFFormaPago.requestFocus();
        }
    }//GEN-LAST:event_jBEditarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
        // TODO add your handling code here:
        if (jLFormaPago.getModel().getSize() > 0) {
            if (JOptionPane.showConfirmDialog(
                    this,
                    "Esta seguro?",
                    "Eliminando Tipo Producto - Nona Mafalda",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                // yes option
                int idFormaPago = jLFormaPago.getSelectedValue().getIdFormaPago();
                boolean exito = false;

                exito = GBDFormaPago.EliminarFormaPago(idFormaPago);

                if (exito) {
                    JOptionPane.showMessageDialog(
                            this,
                            "La Forma de Pago se eliminó correctamente.",
                            "Exito - Nona Mafalda",
                            JOptionPane.INFORMATION_MESSAGE);
                    CargarLista();
                } else {
                    JOptionPane.showConfirmDialog(
                            this,
                            "Intentelo Nuevamente.",
                            "Error al Eliminar el Tipo de Producto - Nona Mafalda",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jBBorrarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:

        HabilitarDeshabilitarCampos(false);
        jLFormaPago.setEnabled(true);

        HabilitarDeshabilitarBotones(true);
        jBGuardar.setEnabled(false);
        jBCancelar.setEnabled(false);

        if (jLFormaPago.getModel().getSize() > 0) {
            jLFormaPago.setSelectedIndex(jLFormaPago.getSelectedIndex());
            SeleccionarItemLista();
        } else {
            jBBorrar.setEnabled(false);
            jBEditar.setEnabled(false);

            LimpiarCampos();
        }

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        if (validar()) {

            int idFormaPago;

            if (banderaAgregarEditar) {
                idFormaPago = -1;
            } else {
                idFormaPago = jLFormaPago.getSelectedValue().getIdFormaPago();
            }

            String nombre = jTFFormaPago.getText();

            CFormaPago formaPago = new CFormaPago(idFormaPago, nombre, true);

            if (banderaAgregarEditar) {
                if (GBDFormaPago.ExisteNombreFormaPagoAgregar(formaPago)) {
                    JOptionPane.showMessageDialog(
                            this,
                            "¡Forma de Pago Repetida!",
                            "Advertencia - Nona Mafalda",
                            JOptionPane.WARNING_MESSAGE);
                    jTFFormaPago.requestFocus();
                    return;
                }
            } else {
                if (GBDFormaPago.ExisteNombreFormaPagoEditar(formaPago)) {
                    JOptionPane.showMessageDialog(
                            this,
                            "¡Forma de Pago Repetida!",
                            "Advertencia - Nona Mafalda",
                            JOptionPane.WARNING_MESSAGE);
                    jTFFormaPago.requestFocus();
                    return;
                }
            }


            boolean exito = false;

            if (idFormaPago == -1) {
                exito = GBDFormaPago.AgregarFormaPago(formaPago);
            } else {
                try {
                    exito = GBDFormaPago.ModificarFormaPago(formaPago);
                } catch (SQLException ex) {
                    Logger.getLogger(JPFormaPago.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            if (exito) {
                JOptionPane.showMessageDialog(
                        this,
                        "La Forma de Pago se guardó Correctamente",
                        "Exito - Nona Mafalda",
                        JOptionPane.INFORMATION_MESSAGE);

                CargarLista();

                for (int i = 0; i < jLFormaPago.getModel().getSize(); i++) {
                    if (jLFormaPago.getModel().getElementAt(i).getFormaPago().equals(nombre)) {
                        jLFormaPago.setSelectedIndex(i);
                    }
                }
            }
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
        banderaAgregarEditar = true;
        LimpiarCampos();

        HabilitarDeshabilitarCampos(true);
        jLFormaPago.setEnabled(false);

        HabilitarDeshabilitarBotones(false);
        jBGuardar.setEnabled(true);
        jBCancelar.setEnabled(true);

        jTFFormaPago.requestFocus();
    }//GEN-LAST:event_jBAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JList<CFormaPago> jLFormaPago;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFFormaPago;
    // End of variables declaration//GEN-END:variables
}
